service: my-lambda-service

provider:
  name: aws
  runtime: provided
  region: us-east-2

functions:
  similarity:
    timeout: 30
    environment:
      ENV_NAME: Docker
    image:
      uri: 221082178166.dkr.ecr.us-east-2.amazonaws.com/mi-repos-lambda-test:latest
    events:
      - http:
          path: similarity
          method: post
          cors: true
